services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - .:/mnt/extra-addons/nn_fund_management
    restart: unless-stopped
    command: --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons -d odoo_dev -u nn_fund_management

volumes:
  odoo-db-data:
  odoo-web-data: